### ISSUE TITLE
Index paths are not actually filtered out

### ISSUE THREAD

**Issue by poke** [ctolkien/SodaPop.RazorPagesSitemap#10]
If you take the standard razor template (`dotnet new razor`) as the base project, then you can see that the sitemap will still contain both routes, once as `http://localhost:5000/Index` and once as `http://localhost:5000/`.

The reason for this is that the filtering is case-sensitive and compared against a lower-case `index`. So `StringComparison.OrdinalIgnoreCase` it is.

But then, none of those routes will be emitted because what is actually being compared here is not the URL but the `ViewEnginePath` which is *“the path of the file without extension, relative to the pages root directory”*, so unrelated to the actual route…

**Comment by poke** [comment]
Not closed yet, as per above. With the fix, the index page will now not appear at all.

– Or is that the desired behavior of the configuration option?

**Comment by ctolkien** [comment]
>With the fix, the index page will now not appear at all.

Well.... shit.

**Comment by ctolkien** [comment]
This is... fixed.. for now. Solution is crap, but it works.
