### ISSUE TITLE
Configure CI and automated builds to Nuget

### ISSUE THREAD

**Issue by ctolkien** [ctolkien/SodaPop.RazorPagesSitemap#7]

**Comment by ctolkien** [comment]
Hitting this issue.

**Comment by ctolkien** [comment]
OK, this is working now via AppVeyor,

FYI @poke 
There is a tag system to handle deployments. Tags pushed with a "v1.2.3" syntax will deploy to both Nuget and Github as a release. Can also use "v1.2.3-betaXYZ" for prerelease builds.

**Comment by poke** [comment]
That’s super cool! Good job! :D
